name = "Prints"
uuid = "f07a6608-fd61-4811-85ec-e1d1721f87b2"
authors = ["Jacob Quinn <quinn.jacobd@gmail.com>"]
version = "0.1.0"

[deps]
Ryu = "5e2e73ce-74d7-11e8-1b43-add1da556067"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
